config/routes.rb
Colchonet::Application.routes.draw do
  resources :rooms
  resources :users
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  root 'home#index'

  get 'gerenciar-quartos'     => 'rooms#index'
  get 'cadastrar-novo-quarto' => 'rooms#new'

  

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :location, :description
  validates_length_of :description, minimum: 30, allow_blank: false
  def complete_name
    "#{title}, #{location}"
  end
end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base  
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  
  has_many :rooms
  
  scope :most_recent, -> { order('created_at DESC') }
  scope :from_rio, -> { where(location: 'Rio de Janeiro') }
  #scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :confirmed, -> { where(confirmed_at: nil) }
  
	validates_presence_of :email, :full_name, :location
	#validates_confirmation_of :password
	validates_length_of :bio, minimum: 30, allow_blank: false
	validates_uniqueness_of :email
	validate :email_format
  
  has_secure_password
  
  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end
  
  def confirm!
    return if confirmed?
    
    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end
  
  def confirmed?
    confirmed_at.present?
  end
	
  private
	# Essa validaçãp pode ser representada da seguinte forma:
	# vlaidate_format_of :email, with: EMAIL_REGEXP

	def email_format
		errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)		
	end
  
  def self.authenticate(email, password)
    user = confirmed.find_by(email: email).try(:authenticate, password)
  end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model
  
  attr_accessor :email, :password
  validates_presence_of :email, :password

  def initialize(session, attributes={})
    @session = session
    @email   = attributes[:email]
    @password= attributes[:password]
  end
  
  def authenticate!
    user = User.authenticate(@email, @password)
    
    if user.present?
      store(user)
    else
      errors.add(:base, 'Erro ao efeturar login')
      false
    end
  end
  
  def store(user)
    @session[:user_id] = user.id
  end
  
  def current_user
    User.find(@session[:user_id])
  end
  
  def user_signed_in?
    @session[:user_id].present?
  end
  
  def destroy
    @session[:user_id] = nil

  def authenticate!
  	user = User.authenticate(@email, @password)
  	if user.present?
  		store(user)
  	else
  		error.add(:base, :invalid_login)
  		false
  	end
  end

  def store(user)
  	@session[:user_id] = user.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  #before_action do
  #  I18n.locale = params[:locale] || I18n.default_locale
  #end
  
  #def default_url_options
  #  { locale: I18n.locale }
  #end
  protect_from_forgery with: :exception
  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?
  
  def user_session
    UserSession.new(session)
  end
  
  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path,
        alert: t('flash.alert.needs_login')
    end
  end
  
  def require_no_authentication
    if user_signed_in?
      redirect_to root_path, notice: t('flash.notcie.already_logged_in')
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])
    
    if user.present?
      user.confirm!
      redirect_to user, notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.take(5)
  end
end  

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_authentication, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
     @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
    @room = current_user.rooms.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    @room = current_user.rooms.find(params[:id])
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render action: 'edit'
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = current_user.rooms.findRoo(params[:id])
    @room.destroy
      
    redirect_to rooms_url 
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy
  
  def new
    @user_session = UserSession.new(session)
  end
  
  def create
    @user_session = UserSession.new(session, params[:user_session])
    if @user_session.authenticate!
      #não esqueça de adicioanr a chave no i18n
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end
  
  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]

  def index
    @users = User.all
  end
  
  def show
		@user = User.find(params[:id])
	end	

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
      Signup.confirm_email(@user).deliver
			redirect_to @user, notice: 'Cadastrado com sucesso.'
		else
			render action: :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user,
			notice: 'Perfil atualizado com sucesso.'
		else
			render action: :edit
		end
	end			 		

	private

	def user_params
		#Os 'pontos' no final da linha não são opcionais
		params.
			require(:user).
			permit(:email, :full_name, :location, :password, :password_confirmation, :bio)
	end
  
  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end
  
  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
        :div,
        model.errors[attribute].first,
        class: 'error_message'
      )
    end
  end
  
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'ativo' : ''
    link_to link_text, link_path, :class => class_name
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<h1>Quartos recem postados</h1>
<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to room.complete_name, room %></li>
  <% end %>  
</ul>

app/views/layouts/_user_navbar.html.erb
        <nav>
          <ul>
            <li><%= nav_link t('layout.new_room'), new_room_path %></li>
            <li><%= nav_link t('layout.rooms'), rooms_path %></li>
            <li><%= nav_link t('layout.my_profile'), user_path(current_user) %></li>
            <li><%= link_to t('layout.signout'), user_sessions_path, method: :delete %></li>
          </ul>
        </nav>

app/views/layouts/_visitor_navbar.html.erb
        <nav>
          <ul>
            <li><%= nav_link t('layout.rooms'), rooms_path %></li>
            <li><%= nav_link t('layout.signup'), new_user_path %></li>
            <li><%= nav_link t('layout.signin'), new_user_sessions_path %></li>
          </ul>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <header>
      <div id="header-wrap">
        <h1><%= link_to "colcho.net", root_path %></h1>
        <% if user_signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/visitor_navbar' %>
        <% end %>
      </div> 
    </header>
    <div id="content">
      <% if notice.present? %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p id="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "erro") %> impediram de salvar o cadastro:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
 </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </p>
  <p>
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to 'Voltar para todos os quartos', rooms_path, :class => "btn btn-default" %>
  </p>
<% end %>

app/views/rooms/_room.html.erb
      <article class="room">
        <h2><%= room.title %></h2>
        <span class="created">
          <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
        </span>
        <p>
          <span class="location">
            <%= link_to room.location, "https://maps.google.com/?q=#{room.location}", target: :blank %>
          </span>
        </p>
        <p>
          <%= room.description %>
        </p>
        <% if belongs_to_user(room) %>
          <p>
            <%= link_to 'Editar', edit_room_path(room), :class => "btn btn-info btn-sm" %> <%= link_to 'Excluir', room, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %>
          </p>
        <% end %>
       </article>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |

app/views/rooms/index.html.erb
<h1><%= t'.title' %></h1>

    <% @rooms.each do |room| %>
      <%= render partial: @rooms, object: current_user.rooms.first %>
    <% end %>

<br>

<%= link_to 'Cadastrar Novo Quarto', 'cadastrar-novo-quarto', :class => "btn btn-primary" %>

app/views/rooms/new.html.erb
<h1>Novo Quarto</h1>

<%= render 'form' %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %></h1>
<p>
  <%= t '.body', full_name: @user.full_name %>
</p>
<p>
  <%= t '.confirm_link_html', link: link_to('@confirmation_link', @confirmation_link) %>
</p>
<p>
  <%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.title' %>

<%= t '.body', full_name: @user.full_name %>

<%= t '.confirm_link_html', link: link_to('@confirmation_link', @confirmation_link) %>

<%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @user_session.errors.has_key? :base %>
  <div id="error_explanation">
    <%= @user_session.errors[:base].join(', ') %>
  </div>
<% end %>

<%= form_for @user_session do |f| %>
  <p>
    <%= f.label "E-mail" %>
    <%= f.text_field :email %>
    <%= error_tag @user_session, :email %>
  </p>
  <p>
    <%= f.label "Senha" %>
    <%= f.password_field :password %>
    <%= error_tag @user_session, :password %>
  </p>
  <p>
    <%= f.submit "Entrar" %>
  </p>
<% end %>
<p><%= link_to t('.sign_up'), new_user_path %></p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<%= t'general.form_error' %>
	</div>
<% end %>		

<%= form_for @user do |f| %>
	<p>
    <%= f.label :full_name %>
		<%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
	</p>
	<p>
    <%= f.label :localization %>
		<%= f.text_field :location %>
    <%= error_tag @user, :location %>
	</p>
	<p>
    <%= f.label :email %>
		<%= f.text_field :email %>
    <%= error_tag @user, :email %>
	</p>
	<p>
    <%= f.label :password %>
		<%= f.password_field :password %>
    <%= error_tag @user, :password %>
	</p>
	<p>
    <%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.label 'Biografia' %>
		<%= f.text_area :bio %>
    <%= error_tag @user, :bio %>
	</p>
	<p>
    <%= f.submit :class => "btn btn-primary btn-sm" %>
	</p>
<% end %>			

app/views/users/edit.html.erb
<h1>Editar perfil</h1>
<%= render 'form' %>
<%= link_to t('links.back'),  @user, {:class => "btn btn-default"} %>

app/views/users/index.html.erb
<h1>Usuários cadastrados</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Exibir', user, :class => "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Editar', edit_user_path(user), :class => "btn btn-info btn-sm" %></td>
        <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Novo Quarto', 'cadastrar-novo-quarto', :class => "btn btn-primary" %>

app/views/users/new.html.erb
<h1><%= t'.title', user_name: @user.full_name %></h1>
<%= render 'form'%>
<%= link_to t('links.back'), root_path, :class => "btn btn-danger btn-sm" %>

app/views/users/show.html.erb
<h1><%= t'.title', user_name: @user.full_name %></h1>
<ul>
  <li><%= t'.location', location: @user.location %></li>
  <li><%= t'.bio', bio: @user.bio %></li>
</ul>
<%= link_to t('.edit'), edit_user_path(@user),  :class => "btn btn-primary btn-sm" %>
<%= link_to 'Home', root_path, :class => "btn btn-danger btn-sm" %>